apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: standard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Choisissez un port disponible
  selector:
    app: pgadmin
