apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector: 
    app: fastapi-app
  type: NodePort
  ports:
    - port: 80 #acces depuis l'exterieur
      targetPort: 5000 # l'api qui communique dans le conteneur
      nodePort: 30005
