apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-hpa  # Nom du HPA
  namespace: standard  # Namespace dans lequel déployer le HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-deployment  # Nom du déploiement à scaler
  minReplicas: 3  # Nombre minimum de réplicas
  maxReplicas: 6  # Nombre maximum de réplicas
  targetCPUUtilizationPercentage: 70  # Seuil d'utilisation CPU pour le scaling

