apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastapi-pv
  namespace: standard
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: default
  hostPath:
    path: /mnt/data/fastapi

