apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: standard
spec:
  capacity:
    storage: 10Gi  # Ajusté à la demande du PVC
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  storageClassName: default

