# Secret pour les identifiants PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
data:
  username: YWRtaW4=  # Encodé en base64 pour 'admin'
  password: c3RvcmVkYg==  # Encodé en base64 pour 'storedb'

